### ISSUE TITLE
Module loses all data sometimes

### ISSUE THREAD

**Issue by snoopy** [orbitalquark/textadept-scratch#1]
I've been using this for a while now and sometimes it loses all data. Unfortunately, I can't reproduce the behavior and was wondering if there are any known bugs that could cause this?
Are there maybe any possible race conditions when using more than one event handler for `events.QUIT`?

**Comment by orbitalquark** [comment]
Sorry to hear :( I cannot think of any race conditions with 
`events.QUIT`. Are you opening additional instances of Textadept (i.e. 
using the `-f` or `--force` command line option)? That might affect 
loading/saving scratch buffers.

**Comment by snoopy** [comment]
I did use another instance with -f but explicitly tested that scenario again and the problem did not materialize. However, if that can cause problems I will just keep it in mind.
